import { mkdir, writeFile } from 'fs/promises';
import { createWriteStream, readFileSync } from 'fs';

import * as simpleIcons from "simple-icons";

function buildContent(icon: simpleIcons.SimpleIcon) {
  // remove <svg>...</svg> from string
  const svg = icon.svg.replace(/<svg[^>]*>/, "").replace(/<\/svg>/, "");

  return `${svg}`;
};

function buildIcon() {
  const baseIconPath = '../base-icon';
  const template = readFileSync('./icon.tsx.template', 'utf8')
    .replace('{{BASE_ICON_REL_PATH}}', baseIconPath);

  return function(name: string, content: string) {    
    return template
      .replace(/{{ICON_NAME}}/g, name)
      .replace('{{CONTENT}}', content);
  };
};

function buildExportLine(name: string, iconsRelPath: string) {
  return `export { default as ${name} } from '${iconsRelPath}${name}';\n`;
}

async function build() {
  // build icons
  const iconsPath = './src/components/icons/';
  const build = buildIcon();

  await mkdir(iconsPath, { recursive: true });
  await Promise.all(Object.keys(simpleIcons).map(name => {
    const icon = simpleIcons[name as keyof typeof simpleIcons];

    const capname = name.replace(/si/g, 'Si');
    return writeFile(`${iconsPath}${capname}.tsx`, build(capname, buildContent(icon)), 'utf8');
  }));

  // export icons
  const baseIconPath = './components/base-icon';
  const indexFile = createWriteStream('./src/index.ts', 'utf8');
  indexFile.write('// This file is auto-generated by build.ts\n');
  indexFile.write(`export * from '${baseIconPath}';\n\n`);
  Object.keys(simpleIcons).forEach(k => {
    const name = k.replace(/si/g, 'Si');
    indexFile.write(buildExportLine(name, './components/icons/'))
  });
  indexFile.close();
}

await build();
